# Adapted from https://raw.githubusercontent.com/ossf/scorecard/main/.github/workflows/scorecard-analysis.yml
name: Scorecard analysis workflow
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 4-6 * * *'
jobs:
  analyze:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed for Code scanning upload
      security-events: write
      # Needed for GitHub OIDC token if publish_results is true
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      
      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.3.3
        with:
          results_file: 'results.sarif'
          results_format: sarif
          publish_results: 'true'
